name: Deployment From Github To AWS
on:
  push:
    branches:
      - main
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Latest Repo
        uses: actions/checkout@v2
        
      - name: Generate Deployment Package 
        run: zip -r deploy.zip * -x "**node_modules**"
  
      - name: Deploy to EB
        uses: einaregilsson/beanstalk-deploy@v19
        with:
          aws_access_key: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws_secret_key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          application_name: ArtemisQL
          environment_name: Artemisql-env
          version_label: "artemisql-v1.2"
          region: us-east-1
          deployment_package: deploy.zip
